### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by PierceMichael** [UndercoverGoose/gimkit#1]
Im using the bookmarklet

**Comment by UndercoverGoose** [comment]
The bookmarklet recently broke, and has been replaced with two new ones that you can find [here](https://undercovergoose.github.io/gimkit/bookmarklet.html). I have confirmed that the new bookmarklets work as intended.

**Comment by PierceMichael** [comment]
> The bookmarklet recently broke, and has been replaced with two new ones that you can find [here](https://undercovergoose.github.io/gimkit/bookmarklet.html). I have confirmed that the new bookmarklets work as intended.

Thx
