### ISSUE TITLE
Page freezes when using bookmarklet

### ISSUE THREAD

**Issue by TheLazySquid** [UndercoverGoose/gimkit#2]
After using bookmarklet one on a gimkit.com/join page, it successfully opens the new tab, but then both the original tab and the new one freeze up. This happens to me when using both chrome and firefox. Strangely, this doesn't happen on other sites, only on Gimkit. Additionally, removing the
```js
if(n.constructor?.name==="WebSocket")return n;
```
part of the bookmarklet stops the page from hanging, but it obviously doesn't prevent the WebSocket object from being frozen.

The same thing happens when using the Userscript.

**Comment by UndercoverGoose** [comment]
Yeah just fixed this, Josh and I are playing a game of cat and mouse so it will crash most of the time until I create a bypass to what Josh implements.
